export const PRODUCT_GET_ALL_PRODUCTS = 'PRODUCT_GET_ALL_PRODUCTS';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const INITIATE_SETTING = 'INITIATE_SETTING';
